jobs:
  detect:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node-version }}
      - if: inputs.install != ''
        run: ${{ inputs.install }}
        working-directory: ${{ inputs.working-directory }}
      - id: detect
        uses: JoshuaKGoldberg/formatly-on-demand@v0
        with:
          mode: detect
          working-directory: ${{ inputs.working-directory }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: formatly-on-demand
          path: ${{ steps.detect.outputs.output-directory }}

name: Formatly on Demand Detect

on:
  workflow_call:
    inputs:
      install:
        description: Command that installs dependencies, such as 'npm ci'.
        required: false
        type: string
      node-version:
        default: lts/*
        description: Node.js version to run the formatter with.
        required: false
        type: string
      working-directory:
        default: .
        description: Directory holding the project to format.
        required: false
        type: string
